[workspace]
authors = ["taiamiti <taiamiti.edmunds@ml4everyone.com>"]
channels = ["conda-forge"]
name = "documentation"
platforms = ["linux-64", "osx-64"]
version = "0.1.0"

[tasks]
build = "mkdocs build"
build-strict = "mkdocs build --strict"
serve = "mkdocs serve"
serve-8010 = "mkdocs serve --dev-addr 127.0.0.1:8010"

[dependencies]
pip = "*"
python = "3.10.*"

[pypi-dependencies]
mkdocs = ">=1.6,<2.0"
mkdocs-material = ">=9.5,<10.0"
mkdocs-git-revision-date-localized-plugin = ">=1.2,<2.0"
mkdocs-redirects = ">=1.2,<2.0"
pymdown-extensions = ">=10.0,<11.0"
pillow = ">=10.0,<11.0"
cairosvg = ">=2.7,<3.0"
